  # vim:sw=2:et:
  dialyzer:
    name: dialyzer
    needs: [checks]
    runs-on: ubuntu-18.04
    steps:
      - name: CHECKOUT REPOSITORY
        if: success() && '$(ERLANG_VERSION_IS)' == 'latest'
        uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-elixir
      - name: CONFIGURE OTP & ELIXIR
        if: success() && '$(ERLANG_VERSION_IS)' == 'latest'
        uses: actions/setup-elixir@v1
        with:
          otp-version: $(ERLANG_VERSION)
          # https://github.com/elixir-lang/elixir/releases
          elixir-version: $(ELIXIR_VERSION)
      - name: CACHE DEPS
        if: success() && '$(ERLANG_VERSION_IS)' == 'latest'
        uses: actions/cache@v1
        with:
          path: deps
          key: otp-$(ERLANG_VERSION)_git-${{ github.sha }}_deps
      - name: CACHE DIALYZER PLT
        if: success() && '$(ERLANG_VERSION_IS)' == 'latest'
        uses: actions/cache@v1
        with:
          path: .$(PROJECT).plt
          key: plt-$(PROJECT)-erlang-$(ERLANG_VERSION)-g${{ github.sha }}
      - name: RUN DIALYZER
        if: success() && '$(ERLANG_VERSION_IS)' == 'latest'
        run: |
          branch_or_tag_name=${GITHUB_REF#refs/*/}
          make dialyze \
            base_rmq_ref=$(base_rmq_ref) \
            current_rmq_ref=$branch_or_tag_name \
            FULL=
